{
  "qualifications": [
    {
      "name": "Maintenance Planner",
      "modules": [],
      "saqa_id": "101874"
    },
    {
      "name": "Quality Controller",
      "modules": [],
      "saqa_id": "117309"
    },
    {
      "name": "Chemical Plant Operator",
      "modules": [],
      "saqa_id": "102156"
    }
  ]
}